// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace NominaPISIB.Infraestructura.AccesoDatos;

public partial class Bonificaciones
{
    public int idBonificaciones { get; set; }

    public int? idEmpleado { get; set; }

    public string BonificacionTipo { get; set; }

    public string BonificacionDescripcion { get; set; }

    public decimal BonificacionMonto { get; set; }

    public DateOnly BonificacionFecha { get; set; }
   
}