// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace NominaPISIB.Infraestructura.AccesoDatos;

public partial class ContratosTipo
{
    public int idContratoTipo { get; set; }

    public string ContratoJornada { get; set; }

    public string ContratoTipoNombre { get; set; }
 
}