// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace NominaPISIB.Infraestructura.AccesoDatos;

public partial class Descuentos
{
    public int idDescuento { get; set; }

    public int? idEmpleado { get; set; }

    public string DescuentoTipo { get; set; }

    public string DescuentoDescripcion { get; set; }

    public decimal DescuentoMonto { get; set; }

    public DateOnly DescuentoFecha { get; set; }
    
}