// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace NominaPISIB.Infraestructura.AccesoDatos;

public partial class Empleados
{
    public int idEmpleado { get; set; }

    public int? FKidPuesto { get; set; }

    public string EmpleadoNombres { get; set; }

    public string EmpleadoApellidos { get; set; }

    public string EmpleadoCedula { get; set; }

    public string EmpleadoCorreo { get; set; }

    public DateOnly EmpleadoFechaNacimiento { get; set; }

    public string EmpleadoEstado { get; set; }

    public string EmpleadoGenero { get; set; }

    public string EmpleadoTelfPersonal { get; set; }

    public DateOnly EmpleadoFechaIngreso { get; set; }
    
}