// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace NominaPISIB.Infraestructura.AccesoDatos;

public partial class Inasistencias
{
    public int idLicencia { get; set; }

    public int idEmpleado { get; set; }

    public DateOnly InasistenciaFecha { get; set; }

    public int? InacistenciaContador { get; set; }
   
}