// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace NominaPISIB.Infraestructura.AccesoDatos;

public partial class Licencias
{
    public int idLicencia { get; set; }

    public string LicenciaNombre { get; set; }

    public int LicenciaRemunerable { get; set; }
    
}