// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace NominaPISIB.Infraestructura.AccesoDatos;

public partial class Nominas
{
    public int idNomina { get; set; }

    public int? idEmpleado { get; set; }

    public int NominaMes { get; set; }

    public int NominaAnio { get; set; }

    public decimal NominaSalarioBase { get; set; }

    public decimal NominaBonificaciones { get; set; }

    public decimal NominaDescuentos { get; set; }

    public decimal NominaSalarioNeto { get; set; }

    public DateOnly NominaFechaEmision { get; set; }
  
}