// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace NominaPISIB.Infraestructura.AccesoDatos;

public partial class Puestos
{
    public int idPuesto { get; set; }

    public string PuestoNombre { get; set; }

    public decimal PuestoSalario { get; set; }

    public int PuestoVacacionesCantidad { get; set; }
   
}